name: Build Documents

on:
  # Scan changed files in PRs (diff-aware scanning):
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  build_en-US_pdf:
    # This job only runs for issue comments, not pull requests
    name: Build PDF
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Branch is ${{ github.ref }}"
      - run: echo "Repo is ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v4
        # with:
        #   lfs: true
      - run: echo "The source commit SHA is ${{ github.sha }}"
      - name: List the files checked out to the build workspace
        run: |
          ls -la ${{ github.workspace }}
      - name: List files under 1.0/blddoc
        run: |
          cd 1.0/blddoc
          ls -la
          cat version_time_stamp.txt
      - name: Call ./owasp_pdf
        run: |
          # ./owasp_pdf -l ASV_en-US
          mkdir -p 1.0/blddoc/en-US/baseline
          cd 1.0/blddoc/en-US/baseline
          echo "PDF_ branch to be created and PF'ed" >> bld_result.txt
          cat bld_result.txt
      - name: Commit the changes
        run:  |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b PDF_${{ github.sha }}
          git add .
          git commit -m "PDF created with the commit ${{ github.sha }}"
          git push --set-upstream origin PDF_${{ github.sha }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request with the geenrated PDF
        run:  |
          gh pr create --base 'main' --head 'PDF_${{ github.sha }}' --title 'Automated Pull Request with PDF' --body 'PDF created with the commit ${{ github.sha }}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Commit the result
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git add . # Stage all changes
      #     git commit -m "Automated PDF Build" # Commit with a message
      #     git push # Push changes to the remote repository
