name: Build Documents

on:
  # Scan changed files in PRs (diff-aware scanning):
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  build_en-US_pdf:
    # This job only runs for issue comments, not pull requests
    name: Build PDF
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Branch is ${{ github.ref }}"
      - run: echo "Repo is ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Get Commit SHA
        run: echo "The commit SHA is ${{ github.sha }}"
      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}
      - name: List files under 1.0/blddoc
        run: |
          cd 1.0/blddoc
          ls -la
          cat version_time_stamp.txt
          ./owasp_pdf -l ASV_en-US
          ls -la asv/en-US/baseline
