name: URL Checker

on:
  pull_request:
    paths:
      - '1.0/**'
  push:
    branches:
      - main
    paths:
      - '1.0/**'
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set options
        id: options
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "check-modified-files-only=yes" >> $GITHUB_OUTPUT
            echo "use-verbose-mode=yes" >> $GITHUB_OUTPUT
          else
            echo "check-modified-files-only=no" >> $GITHUB_OUTPUT
            echo "use-verbose-mode=no" >> $GITHUB_OUTPUT
          fi

      - name: Check URLs
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          check-modified-files-only: ${{ steps.options.outputs.check-modified-files-only }}
          config-file: .github/workflows/config/url-checker-config.json
          folder-path: '1.0'
          use-quiet-mode: yes
          use-verbose-mode: ${{ steps.options.outputs.use-verbose-mode }}
